### ISSUE TITLE
[Bug] Failed checks while deploying standby cluster

### ISSUE THREAD

**Issue by lcoon21** [vitabaks/autobase#1083]
### Bug description

I'm deploying standby cluster which replicates from external postgresql node

I have in my all.yml

```
patroni_standby_cluster:
  host: "172.16.8.14" # an address of remote master
  port: "5432" # a port of remote master
  primary_slot_name: "standby_slot"  # which slot on the remote master to use for replication (optional)
  restore_command: "pgbackrest --stanza=example archive-get %f %p"  # command to restore WAL records from the remote master to standby leader (optional)
  create_replica_methods:
    - pgbackrest
```

And at first I tried to set the hosts like this at hosts.ini

```
[master]
172.16.8.7 hostname=db-1 postgresql_exists=false

[replica]
172.16.8.8 hostname=db-2 postgresql_exists=false 
172.16.8.9 hostname=db-3 postgresql_exists=false
```

### Expected behavior

And now I expect that tasks are going to consider this option , while my configuration includes `patroni_standby_cluster` option, but in tasks like this:

```
- block: # PITR (custom bootstrap) - password reset for PostgreSQL users
    - name: Make sure the Master is not in recovery mode
      ansible.builtin.command: >-
        {{ postgresql_bin_dir }}/psql -p {{ postgresql_port }} -U {{ patroni_superuser_username }} -d postgres -tAXc
        "select pg_is_in_recovery()"
      register: pg_is_in_recovery
      until: pg_is_in_recovery.stdout == "f"
      retries: "{{ (cluster_restore_timeout | default(86400)) | int // 30 }}" # timeout 24 hours
      delay: 30
      changed_when: false
      when: inventory_hostname == groups['master'][0]
```

It's impossible cuz when it's standby cluster then all the nodes are standby, so the condition can't be performed.

If I set in hosts.ini all the nodes as replica like this:

```
[replica]
172.16.8.7 hostname=db-1 postgresql_exists=false
172.16.8.8 hostname=db-2 postgresql_exists=false 
172.16.8.9 hostname=db-3 postgresql_exists=false
```

I see new failures because there's no object in [master] dict:

`fatal: [172.16.8.9]: FAILED! => {"msg": "The conditional check 'inventory_hostname == groups['master'][0]' failed. The error was: error while evaluating conditional (inventory_hostname == groups['master'][0]): 'dict object' has no attribute 'master'\n\nThe error appears to be in '/home/runner/_work/appbonus-ansible/appbonus-ansible/postgres/ansible_collections/vitabaks/autobase/roles/pre_checks/tasks/pgbouncer.yml': line 4, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# It loops through the 'postgresql_parameters' list and, if 'max_connections' is found in the option, it sets the 'max_connections' value accordingly.\n- name: Set max_connections from vars or use default\n  ^ here\n"}`

 A lot of tasks base on check the 0 element of this dict:

```
- name: Set max_connections from vars or use default
  ansible.builtin.set_fact:
    max_connections: "{{ (item.value | default(100)) | int }}"
  loop: "{{ postgresql_parameters | default([]) }}"
  when:
    - inventory_hostname == groups['master'][0]
    - item.option == "max_connections"
```

### Steps to reproduce

1. patroni_standby_cluster option
2. fill [master] and [replica] at hosts.ini

### Installation method

Command line

### System info

My ansible-core version 2.17.12
Ubuntu 22.04 github runner
