### ISSUE TITLE
Automate the scaling of DCS cluster nodes (etcd, consul)

### ISSUE THREAD

**Issue by vitabaks** [vitabaks/autobase#503]
Currently, scaling of Postgres nodes using playbook `add_pgnode.yml` and scaling of HAProxy nodes using playbook `add_balancer.yml` is implemented, but for etcd or consul cluster, only the initial deploument is automated and further maintenance needs to be done manually, for example, replacing a failed node or scaling a DCS cluster.

Automate the scaling of DCS cluster nodes

- [x] ETCD cluster
- [ ] Consul cluster

---
Consider sponsoring the project via [GitHub](https://github.com/sponsors/vitabaks) or [Patreon](https://patreon.com/vitabaks)

**Comment by m3ki** [comment]
I am not sure if this would help, but I believe I was able to replace a dead etcd node by doing the following:

on any non dead node remove existing node like so:
```bash
export ETCDCTL_API=3
HOST_1=10.10.10.77
HOST_2=10.10.10.78
HOST_3=10.10.10.79
ENDPOINTS=$HOST_1:2379,$HOST_2:2379,$HOST_3:2379
```
Get node dead node id
```bash
etcdctl --endpoints=$ENDPOINTS member list
etcdctl --endpoints=$ENDPOINTS endpoint health
etcdctl --write-out=table --endpoints=$ENDPOINTS endpoint status
```

Remove dead node
```bash
etcdctl member remove {NODE ID HERE}
```

readd new node
```bash
etcdctl member add ffs-node03 --peer-urls=http://10.10.10.79:2380
```

Now I had to modify ansible etcd playbook to change etcd user directory to something else of that of etcd data directory like so
add/modify following after etcd data directory
```yaml
- name: Add etcd user
  ansible.builtin.user:
    name: etcd
    shell: /usr/sbin/nologin
    home: "{{ etcd_user_dir }}"
  tags: etcd, etcd_conf

- name: Create etcd user directory
  ansible.builtin.file:
    path: "{{ etcd_user_dir }}"
    state: directory
    owner: etcd
    mode: "0700"
  tags: etcd, etcd_conf
```

modify etcd.conf template
```yaml
ETCD_INITIAL_CLUSTER_STATE="{{ 'existing' if new_node | default(false) | bool else 'new' }}"
```

Then rerun etcd playbook like this
```make
```
