### ISSUE TITLE
Console (UI/API): Export cluster to ansible inventory file

### ISSUE THREAD

**Issue by arpbs-nsain** [vitabaks/autobase#804]
I have used the console UI to create a custom Postgresql cluster on local VMs and would now like to manage it using Ansible CLI and the automation playbooks in this repository. Is there an API endpoint that I can use to export my cluster configuration in a format I can use with the Ansible playbooks?

Thanks,
Nathan

**Comment by vitabaks** [comment]
PostgreSQL Cluster Console API https://postgresql-cluster.readme.io

**Comment by vitabaks** [comment]
If you're interested in this feature, please consider becoming a [sponsor](https://autobase.tech/docs/sponsor).

The development of this feature requires sponsorship to fund developer efforts. If you're already a sponsor and are interested in this feature, please leave a comment here so we can prioritize this issue accordingly.

We also welcome contributions from those willing to dedicate their time to implement this feature on a voluntary basis. Please see the [Contributing Guide](https://github.com/vitabaks/autobase/blob/master/CONTRIBUTING.md) for more information.

**Comment by vitabaks** [comment]
/bounty 25

Increase to $75

**Comment by vitabaks** [comment]
## Proposed implementation

Add “**Export to inventory**” to the Actions menu in the Clusters table, placing it above “Remove from list”.

![Image](https://github.com/user-attachments/assets/9d721154-5899-4eb0-9a33-225bcf1becd4)

Details:

The Autobase UI can generate an inventory in JSON format and passes it to the API service via the `ANSIBLE_INVENTORY_JSON` variable to initiate the cluster deployment process in the “Your Own Machines” mode. The API service then creates a corresponding entry in the [clusters](https://github.com/vitabaks/autobase/blob/2.2.0/console/db/migrations/20240520144338_2.0.0_initial_scheme_setup.sql#L664) table, including any specified variables in the `extra_vars` column. After the deployment is complete, the service inserts server details into the [servers](https://github.com/vitabaks/autobase/blob/2.2.0/console/db/migrations/20240520144338_2.0.0_initial_scheme_setup.sql#L760) table and links them to the cluster. We can use this to generate an up-to-date list of nodes for the inventory (postgres_cluster group)

To support inventory export, the API can be extended to retrieve values from the servers and clusters tables and generate an inventory file in YAML format (for better readability and compatibility). This will enable users to continue managing the deployed cluster via the command line or integrate it into GitOps workflows.

Example:

```
postgres=# select * from clusters where cluster_name = 'prod-frontend-db'\gx
-[ RECORD 1 ]-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
cluster_id          | 75
project_id          | 2
environment_id      | 1
secret_id           | 
cluster_name        | prod-frontend-db
cluster_status      | unavailable
cluster_description | 
cluster_location    | us-east-1
connection_info     | {"port": "6432", "address": {"primary": "internal-prod-frontend-db-primary-563341955.us-east-1.elb.amazonaws.com", "replica": "internal-prod-frontend-db-replica-1806399780.us-east-1.elb.amazonaws.com"}, "password": "O3R2CFeP2jhuKo0VeQ1aO3tysSYj3zfw", "superuser": "postgres"}
extra_vars          | ["cloud_provider=aws", "server_type=t3.small", "server_location=us-east-1", "server_count=3", "volume_size=110", "ssh_public_keys='ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAgEA0TU9YoE5MwvOKKxpGn8CoU4bkd2Lh5JNSN5/B/UGWGAp0tzKIOEMZVpgIORtpwVQyk6witW2eLjiPxDP5TR19ql0dae4JrR0tstnoXxcuhQYDLhtcJ7TVjpflQYjJjjmO7WaVyl4DwuwizUDO+h8zryu7W8eIUaJoPo8TgMtqLxZqjZRT43G3BUsTfH/Imp3MmgwGY2/rkLAZ8fJtLVvReR3PFs5uUmnWqTdLLRgNzlxcfFlUySFXVvbeCAg/srGrAvAYPVMknorifCIVSvnCCMUVvScChBkHX34j6TWe/VX3phYNR+Ps0TM0R59yevbanFX3bj3fdGq8WD5L6Rjdcbb7Mh/NPAh2hz8+sB57yangPmBspgW0BcLgj2Q44EpfODpKLsh8CGI/6g63EoI0Uq8b7EBJpwvcEWYTsrnI7VtC9fNlrMbhHjKKj+R0eQ7uQxeCHfnnKRA4OthE51OhhyfIE1RDLA6YLyP5iIEAvPqwX1UnfvFCMfOur7Y93iHp9MahCs1nzRFK4Vluu9lJWqwgAFiZL5szvx6IyTonRQBZfpPxGqHVdlBFMsucuIRnTBcgGYlKHAzKCMEQMgXDn4jeLUzA+2mhhxIaTufcvgX9kfcyLni4ceO6/w+YyNozpEzbGg63wX2uPq35NlVL6Bn/whzcMINzKKCc7AVGbk='", "ansible_user=ubuntu", "postgresql_version=17", "patroni_cluster_name=prod-frontend-db", "server_image=ami-063fb82b183efe67d", "patroni_cluster_name=prod-frontend-db"]
inventory           | 
server_count        | 3
postgres_version    | 17
created_at          | 2025-05-28 12:07:04.046001
updated_at          | 2025-06-16 10:02:43.39435
deleted_at          | 
flags               | 1

postgres=# select * from servers where cluster_id = 75;
 server_id | cluster_id |   server_name    | server_location | server_role | server_status |  ip_address   | timeline | lag | tags | pending_restart |         created_at         |         updated_at         
-----------+------------+------------------+-----------------+-------------+---------------+---------------+----------+-----+------+-----------------+----------------------------+----------------------------
       118 |         75 | ip-172-31-46-120 | us-east-1       | N/A         | N/A           | 172.31.46.120 |          |     |      | f               | 2025-05-28 12:16:47.798698 | 2025-06-16 10:05:52.507733
       120 |         75 | ip-172-31-41-227 | us-east-1       | N/A         | N/A           | 172.31.41.227 |          |     |      | f               | 2025-05-28 12:16:47.802038 | 2025-06-16 10:05:52.509193
       119 |         75 | ip-172-31-41-84  | us-east-1       | N/A         | N/A           | 172.31.41.84  |          |     |      | f               | 2025-05-28 12:16:47.801497 | 2025-06-16 10:05:52.509647
(3 rows)
```

Example of a file `inventory` file:

```yaml
all:
  vars:
    cloud_provider: aws
    server_type: t3.small
    server_location: us-east-1
    server_count: 3
    volume_size: 110
    ssh_public_keys: 'ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAgEA0TU9YoE5MwvOKKxpGn8CoU4bkd2Lh5JNSN5/B/UGWGAp0tzKIOEMZVpgIORtpwVQyk6witW2eLjiPxDP5TR19ql0dae4JrR0tstnoXxcuhQYDLhtcJ7TVjpflQYjJjjmO7WaVyl4DwuwizUDO+h8zryu7W8eIUaJoPo8TgMtqLxZqjZRT43G3BUsTfH/Imp3MmgwGY2/rkLAZ8fJtLVvReR3PFs5uUmnWqTdLLRgNzlxcfFlUySFXVvbeCAg/srGrAvAYPVMknorifCIVSvnCCMUVvScChBkHX34j6TWe/VX3phYNR+Ps0TM0R59yevbanFX3bj3fdGq8WD5L6Rjdcbb7Mh/NPAh2hz8+sB57yangPmBspgW0BcLgj2Q44EpfODpKLsh8CGI/6g63EoI0Uq8b7EBJpwvcEWYTsrnI7VtC9fNlrMbhHjKKj+R0eQ7uQxeCHfnnKRA4OthE51OhhyfIE1RDLA6YLyP5iIEAvPqwX1UnfvFCMfOur7Y93iHp9MahCs1nzRFK4Vluu9lJWqwgAFiZL5szvx6IyTonRQBZfpPxGqHVdlBFMsucuIRnTBcgGYlKHAzKCMEQMgXDn4jeLUzA+2mhhxIaTufcvgX9kfcyLni4ceO6/w+YyNozpEzbGg63wX2uPq35NlVL6Bn/whzcMINzKKCc7AVGbk='
    ansible_user: ubuntu
    server_image: ami-063fb82b183efe67d
    postgresql_version: 17
    patroni_cluster_name: prod-frontend-db
  children:
    master:
      hosts:
        172.31.46.120:
          hostname: ip-172-31-46-120
          postgresql_exists: true
    replica:
      hosts:
        172.31.41.227:
          hostname: ip-172-31-41-227
          postgresql_exists: true
        172.31.41.84:
          hostname: ip-172-31-41-84
          postgresql_exists: true
    postgres_cluster:
      children:
        master: {}
        replica: {}
    etcd_cluster:
      hosts:
        172.31.46.120: {}
        172.31.41.227: {}
        172.31.41.84: {}
    balancers:
      hosts: {}
```
- the balancers group contains nodes from the master and replica groups - only if the with_haproxy_load_balancing=true variable is defined
- the etcd_cluster group contains nodes from the master and replica groups
- postgresql_exists is set to true because it is already a deployed cluster.

Source code:
- UI: https://github.com/vitabaks/autobase/tree/master/console/ui
- API: https://github.com/vitabaks/autobase/tree/master/console/service

API Reference: https://autobase.readme.io/

Ansible doc: https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html
