### ISSUE TITLE
Stanza not created when adding PGBackRest after initial deployment

### ISSUE THREAD

**Issue by Hannsre** [vitabaks/autobase#874]
### Bug description

Hello,

I just noticed a possibly minor bug when editing an existing cluster deployment. 
I set up a new Cluster but forgot to add backups using pgbackrest. So I edited the `automation/vars/main.yml` to include pgbackrest with the neccesary details, then ran `ansible-playbook config_pgcluster.yml` which did add the pgbackrest config, but it did not create a stanza so backups would fail. There were no errors during deployment.

Redeploying the Cluster from Scratch with the same config results in a working pgbackrest config. 

My pgbackrest block: 

```
# pgBackRest
pgbackrest_install: true  # or 'true' to install and configure backups using pgBackRest
pgbackrest_install_from_pgdg_repo: true  # or 'false'
pgbackrest_stanza: "{{ patroni_cluster_name }}"  # specify your --stanza
pgbackrest_repo_type: "s3"  # or "s3", "gcs", "azure"
pgbackrest_repo_host: ""  # dedicated repository host (optional)
pgbackrest_repo_user: "postgres"  # if "repo_host" is set (optional)
pgbackrest_conf_file: "/etc/pgbackrest/pgbackrest.conf"
# config https://pgbackrest.org/configuration.html
pgbackrest_conf:
  global:  # [global] section
    - { option: "log-level-file", value: "detail" }
    - { option: "log-path", value: "/var/log/pgbackrest" }
    - { option: "repo1-type", value: "{{ pgbackrest_repo_type | lower }}" }
    - { option: "repo1-path", value: "/pgbackrest" }  # logical path in bucket
    - { option: "repo1-s3-key", value: "{{ s3_access_key }}" }  # change this value
    - { option: "repo1-s3-key-secret", value: "{{ s3_secret_key }}" }  # change this value
    - { option: "repo1-s3-bucket", value: "bucket-name" }  # change this value
    - { option: "repo1-s3-endpoint", value: "minio-fqdn/bucket-name" }  # change this value
    - { option: "repo1-s3-region", value: "region-name" }  # change this value
    - { option: "repo1-s3-uri-style", value: "path" }  # change this value    
    # - { option: "repo1-path", value: "/var/lib/pgbackrest" }
    - { option: "repo1-retention-full", value: "4" }
    - { option: "repo1-retention-archive", value: "4" }
    - { option: "repo1-bundle", value: "y" }
    - { option: "repo1-block", value: "y" }
    - { option: "start-fast", value: "y" }
    - { option: "stop-auto", value: "y" }
    - { option: "link-all", value: "y" }
    - { option: "resume", value: "n" }
    - { option: "spool-path", value: "/var/spool/pgbackrest" }
    - { option: "archive-async", value: "y" } # Enables asynchronous WAL archiving (details: https://pgbackrest.org/user-guide.html#async-archiving)
    - { option: "archive-get-queue-max", value: "1GiB" }
#    - { option: "archive-push-queue-max", value: "100GiB" }
#    - { option: "backup-standby", value: "y" } # When set to 'y', standby servers will be automatically added to the stanza section.
#    - { option: "", value: "" }
  stanza:  # [stanza_name] section
    - { option: "process-max", value: "4" }
    - { option: "log-level-console", value: "info" }
    - { option: "recovery-option", value: "recovery_target_action=promote" }
    - { option: "pg1-socket-path", value: "{{ postgresql_unix_socket_dir }}" }
    - { option: "pg1-path", value: "{{ postgresql_data_dir }}" }
#    - { option: "", value: "" }
```
I also changed the cron settings for diff backups: 
```
  - name: "pgBackRest: Diff Backup"
    file: "/etc/cron.d/pgbackrest-{{ patroni_cluster_name }}"
    user: "postgres"
    minute: "00"
    hour: "/2"
    day: "*"
    month: "*"
    weekday: "0"
    job: "pgbackrest --stanza={{ pgbackrest_stanza }} --type=diff backup"
    # job: "if [ $(psql -tAXc 'select pg_is_in_recovery()') = 'f' ]; then pgbackrest --stanza={{ pgbackrest_stanza }} --type=diff backup; fi"
```

### Expected behavior

From [the docs](https://autobase.tech/docs/management/configuration) I'd expect the stanza to be created automatically after adding the backup config. 

### Steps to reproduce

1. Deploy a new cluster without pgbackrest set up
2. Change the `automation/vars/main.yml` to include pgbackrest for backups.
3. Deploy the changes running `ansible-playbook config_pgcluster.yml`.
4. Test backup functionality on the hosts, e.g. by running `sudo -u postgres pgbackrest --stanza=stanza-name --type=diff backup`

### Installation method

Console (UI)

### System info

OS: Debian 12 VMs, kernel 6.1.123-1
Autobase Version: 2.1.0
A total of 3 VMs running on Proxmox 8.3
