### ISSUE TITLE
Console via an external proxy (Traefik, Caddy)

### ISSUE THREAD

**Issue by vasyakrg** [vitabaks/autobase#876]
### Bug description

We have traefik on the host machine, run the application and specify labels with two separate connection points. 
we get this error on some tabs:

1) /settings/general

<img width="1479" alt="Image" src="https://github.com/user-attachments/assets/f323ac82-234a-4be7-ac93-4bd6052fff00" />

2) /settings/projects

<img width="1586" alt="Image" src="https://github.com/user-attachments/assets/1307361a-9e7f-483b-a099-c073f6473e9c" />

On other tabs it seems to work and even clusters are created

### Expected behavior

Here, for example, everything is correct and there are no errors

<img width="1208" alt="Image" src="https://github.com/user-attachments/assets/def271bc-6314-4594-b2cb-f8b7f2939ffe" />

### Steps to reproduce

docker-compose yaml

```
services:
  pg-console:
    image: vitabaks/postgresql_cluster_console:latest
    container_name: pg-console
    restart: unless-stopped
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.pg-console-web.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.pg-console-web.entrypoints=https"
      - "traefik.http.routers.pg-console-web.service=pg-console-web"
      - "traefik.http.routers.pg-console-web.tls=true"
      - "traefik.http.routers.pg-console-web.tls.certresolver=letsEncrypt"
      - "traefik.http.services.pg-console-web.loadbalancer.server.port=80"

      - "traefik.http.routers.pg-console-api.rule=Host(`${DOMAIN}`) && PathPrefix(`/api/v1`)"
      - "traefik.http.routers.pg-console-api.entrypoints=https"
      - "traefik.http.routers.pg-console-api.service=pg-console-api"
      - "traefik.http.routers.pg-console-api.tls=true"
      - "traefik.http.routers.pg-console-api.tls.certresolver=letsEncrypt"
      - "traefik.http.services.pg-console-api.loadbalancer.server.port=8080"
      - "traefik.docker.network=webproxy"
    environment:
      - PG_CONSOLE_API_URL=${PG_CONSOLE_API_URL}
      - PG_CONSOLE_AUTHORIZATION_TOKEN=${PG_CONSOLE_AUTH_TOKEN}
      - PG_CONSOLE_DOCKER_IMAGE=${PG_CONSOLE_DOCKER_IMAGE}
    volumes:
      - console_postgres:/var/lib/postgresql
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/ansible:/tmp/ansible
    networks:
      - pg-console-network
      - webproxy

volumes:
  console_postgres:

networks:
  pg-console-network:
    name: pg-console-network
  webproxy:
    name: webproxy
    external: true
```
.env

```
DOMAIN=pg-console.domain.com

PG_CONSOLE_API_URL=https://pg-console.domain.com/api/v1
PG_CONSOLE_AUTH_TOKEN=secret
PG_CONSOLE_DOCKER_IMAGE=vitabaks/postgresql_cluster:latest
```

### Installation method

GitOps

### System info

root@docker:/srv# docker version
Client: Docker Engine - Community
 Version:           27.3.1
Server: Docker Engine - Community
 Engine:
  Version:          27.3.1

root@docker:/srv# docker exec traefik traefik version
Version:      3.2.0

root@docker:/srv# cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.5 LTS"

**Comment by sbusso** [comment]
I concur there are strange behaviors in the UI when used behind a reverse proxy. In my case I use Caddy, after creating a project, the UI makes 16 requests to get the list of projects but ultimately shows an empty list of projects. 

<img width="813" alt="Image" src="https://github.com/user-attachments/assets/a3601093-4f28-40bc-82c6-a10307b7429b" />

**Comment by sbusso** [comment]
There are javascript errors but the only thing showing is 

<img width="663" alt="Image" src="https://github.com/user-attachments/assets/8fbc6cd1-bda9-46ac-82ed-80969fc5bf97" />

in `/assets/index-DAYNtIUu.js:356:37014`

**Comment by vitabaks** [comment]
Make sure that your proxy is correctly configured to forward requests to the service’s API, which listens on port 8080 [by default](https://github.com/vitabaks/autobase/tree/master/console/service#configuration). Then, set the PG_CONSOLE_API_URL variable to the correct proxy address for the API.

**Comment by vitabaks** [comment]
In the near future, I will try to test the setup using Caddy proxy.

**Comment by sbusso** [comment]
> Make sure that your proxy is correctly configured to forward requests to the service’s API, which listens on port 8080 [by default](https://github.com/vitabaks/autobase/tree/master/console/service#configuration). Then, set the PG_CONSOLE_API_URL variable to the correct proxy address for the API.

I did, and the previous example shows a project being created by the API. Sometimes I get some data back by forcing the refreshing of the page, but mostly javascript errors. Here is a config that should help replicate the problem with Caddy:

```yaml
# docker network create caddy

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped
    labels: # Global options
      caddy.email: ${EMAIL}
    

networks:
  caddy:
    external: true

volumes:
  caddy_data: {}
```

```yaml
services:
  pg-console:
    image: autobase/console:latest
    container_name: pg-console
    restart: unless-stopped
    labels:
      caddy: ${PG_CONSOLE_DOMAIN}
      caddy.@api.path: /api/v1/*
      caddy.0_reverse_proxy: "@api {{upstreams 8080}}"
      caddy.1_reverse_proxy: "{{upstreams 80}}"

    environment:
      - PG_CONSOLE_API_URL=${PG_CONSOLE_API_URL}
      - PG_CONSOLE_AUTHORIZATION_TOKEN=${PG_CONSOLE_AUTH_TOKEN}
    volumes:
      - console_postgres:/var/lib/postgresql
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - caddy

volumes:
  console_postgres:


networks:
  caddy:
    name: caddy
    external: true
```
